package main

type Model struct {
	Latitude           []float64 `json:"latitude"`
	Longitude          []float64 `json:"longitude"`
	Elevation          []float64 `json:"elevation,omitempty"`
	Hourly             []string  `json:"hourly,omitempty"`
	Daily              []string  `json:"daily,omitempty"`
	Current            []string  `json:"current,omitempty"`
	TemperatureUnit    string    `json:"temperature_unit,omitempty"`
	WindSpeedUnit      string    `json:"wind_speed_unit,omitempty"`
	PrecipitationUnit  string    `json:"precipitation_unit,omitempty"`
	Timeformat         string    `json:"timeformat,omitempty"`
	Timezone           []string  `json:"timezone,omitempty"`
	PastDays           int       `json:"past_days,omitempty"`
	ForecastDays       int       `json:"forecast_days,omitempty"`
	ForecastHours      int       `json:"forecast_hours,omitempty"`
	ForecastMinutely15 int       `json:"forecast_minutely_15,omitempty"`
	PastHours          int       `json:"past_hours,omitempty"`
	PastMinutely15     int       `json:"past_minutely_15,omitempty"`
	StartDate          string    `json:"start_date,omitempty"`
	EndDate            string    `json:"end_date,omitempty"`
	StartHour          string    `json:"start_hour,omitempty"`
	EndHour            string    `json:"end_hour,omitempty"`
	StartMinutely15    string    `json:"start_minutely_15,omitempty"`
	EndMinutely15      string    `json:"end_minutely_15,omitempty"`
	Models             []string  `json:"models,omitempty"`
	CellSelection      string    `json:"cell_selection,omitempty"`
	Apikey             string    `json:"apikey,omitempty"`
}

type Hourly struct {
	Temperature2m            float64 `json:"temperature_2m"`
	RelativeHumidity2m       float64 `json:"relative_humidity_2m"`
	DewPoint2m               float64 `json:"dew_point_2m"`
	ApparentTemperature      float64 `json:"apparent_temperature"`
	PressureMsl              float64 `json:"pressure_msl"`
	SurfacePressure          float64 `json:"surface_pressure"`
	CloudCover               float64 `json:"cloud_cover"`
	CloudCoverLow            float64 `json:"cloud_cover_low"`
	CloudCoverMid            float64 `json:"cloud_cover_mid"`
	CloudCoverHigh           float64 `json:"cloud_cover_high"`
	WindSpeed10m             float64 `json:"wind_speed_10m"`
	WindSpeed80m             float64 `json:"wind_speed_80m"`
	WindSpeed120m            float64 `json:"wind_speed_120m"`
	WindSpeed180m            float64 `json:"wind_speed_180m"`
	WindDirection10m         float64 `json:"wind_direction_10m"`
	WindDirection80m         float64 `json:"wind_direction_80m"`
	WindDirection120m        float64 `json:"wind_direction_120m"`
	WindDirection180m        float64 `json:"wind_direction_180m"`
	WindGusts10m             float64 `json:"wind_gusts_10m"`
	ShortwaveRadiation       float64 `json:"shortwave_radiation"`
	DirectRadiation          float64 `json:"direct_radiation"`
	DirectNormalIrradiance   float64 `json:"direct_normal_irradiance"`
	DiffuseRadiation         float64 `json:"diffuse_radiation"`
	GlobalTiltedIrradiance   float64 `json:"global_tilted_irradiance"`
	VapourPressureDeficit    float64 `json:"vapour_pressure_deficit"`
	Cape                     float64 `json:"cape"`
	Evapotranspiration       float64 `json:"evapotranspiration"`
	Et0FaoEvapotranspiration float64 `json:"et0_fao_evapotranspiration"`
	Precipitation            float64 `json:"precipitation"`
	Snowfall                 float64 `json:"snowfall"`
	PrecipitationProbability float64 `json:"precipitation_probability"`
	Rain                     float64 `json:"rain"`
	Showers                  float64 `json:"showers"`
	WeatherCode              int     `json:"weather_code"`
	SnowDepth                float64 `json:"snow_depth"`
	FreezingLevelHeight      float64 `json:"freezing_level_height"`
	Visibility               float64 `json:"visibility"`
	SoilTemperature0cm       float64 `json:"soil_temperature_0cm"`
	SoilTemperature6cm       float64 `json:"soil_temperature_6cm"`
	SoilTemperature18cm      float64 `json:"soil_temperature_18cm"`
	SoilTemperature54cm      float64 `json:"soil_temperature_54cm"`
	SoilMoisture0To1cm       float64 `json:"soil_moisture_0_to_1cm"`
	SoilMoisture1To3cm       float64 `json:"soil_moisture_1_to_3cm"`
	SoilMoisture3To9cm       float64 `json:"soil_moisture_3_to_9cm"`
	SoilMoisture9To27cm      float64 `json:"soil_moisture_9_to_27cm"`
	SoilMoisture27To81cm     float64 `json:"soil_moisture_27_to_81cm"`
	IsDay                    int     `json:"is_day"`
}

type Minutely15 struct {
	Temperature2m                 float64 `json:"temperature_2m"`
	RelativeHumidity2m            float64 `json:"relative_humidity_2m"`
	DewPoint2m                    float64 `json:"dew_point_2m"`
	ApparentTemperature           float64 `json:"apparent_temperature"`
	ShortwaveRadiation            float64 `json:"shortwave_radiation"`
	DirectRadiation               float64 `json:"direct_radiation"`
	DirectNormalIrradiance        float64 `json:"direct_normal_irradiance"`
	GlobalTiltedIrradiance        float64 `json:"global_tilted_irradiance"`
	GlobalTiltedIrradianceInstant float64 `json:"global_tilted_irradiance_instant"`
	DiffuseRadiation              float64 `json:"diffuse_radiation"`
	SunshineDuration              float64 `json:"sunshine_duration"`
	LightningPotential            float64 `json:"lightning_potential"`
	Precipitation                 float64 `json:"precipitation"`
	Snowfall                      float64 `json:"snowfall"`
	Rain                          float64 `json:"rain"`
	Showers                       float64 `json:"showers"`
	SnowfallHeight                float64 `json:"snowfall_height"`
	FreezingLevelHeight           float64 `json:"freezing_level_height"`
	Cape                          float64 `json:"cape"`
	WindSpeed10m                  float64 `json:"wind_speed_10m"`
	WindSpeed80m                  float64 `json:"wind_speed_80m"`
	WindDirection10m              float64 `json:"wind_direction_10m"`
	WindDirection80m              float64 `json:"wind_direction_80m"`
	WindGusts10m                  float64 `json:"wind_gusts_10m"`
	Visibility                    float64 `json:"visibility"`
	WeatherCode                   int     `json:"weather_code"`
}
